# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edfde390e7b3f7d6c2fd6c87e373df0f87811238c95645197be8c809e94f4c7c58d6d15f044445b44f6e6c2d8eff90ee1cffd330d4604f62cb7c0dbd9a2a5c0e

test:
  secret_key_base: 6320ef2b9d2b8d56fe6c8b895f377377aaac70e2107fbf0b9a360da57f876f7399bb7478fa231ca5d8fc0c55e67579bf123a321718de117def65cdd326cd4022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
